import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'category',
      label: '📖 Start Here',
      collapsed: false,
      items: ['start-here', 'course-overview'],
    },
    {
      type: 'category',
      label: '🤖 Module 1 — Foundations',
      collapsed: false,
      items: ['physical-ai-foundations', 'sensors-perception'],
    },
    {
      type: 'category',
      label: '🌐 Module 2 — ROS 2',
      collapsed: true,
      items: [
        'ros2-intro',
        'ros2-nodes-topics-services',
        'ros2-actions-nav2',
      ],
    },
    {
      type: 'category',
      label: '🌍 Module 3 — Simulation',
      collapsed: true,
      items: ['gazebo-digital-twin', 'unity-visualization'],
    },
    {
      type: 'category',
      label: '⚡ Module 4 — NVIDIA Isaac',
      collapsed: true,
      items: ['isaac-sim-synthetic-data', 'isaac-ros-vslam'],
    },
    {
      type: 'category',
      label: '🧠 Module 5 — VLA & AI',
      collapsed: true,
      items: [
        'vla-overview',
        'voice-to-action-whisper',
        'llm-planning-to-ros',
      ],
    },
    {
      type: 'category',
      label: '🏆 Module 6 — Capstone',
      collapsed: true,
      items: ['capstone-autonomous-humanoid'],
    },
    {
      type: 'category',
      label: '📚 Reference',
      collapsed: true,
      items: ['glossary', 'references'],
    },
  ],

  // Legacy sidebar — existing tutorial docs remain accessible
  tutorialSidebar: [
    'intro',
    'hackathon',
    'chatbot',
    {
      type: 'category',
      label: 'Tutorial - Basics',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
